{
 "title": "Tobira",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Build Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "tobira_build_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(tobira_http_requests_total[1m])*60",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Sync lag",
   "type": "timeseries",
   "description": "How far Tobira's database is behind Opencast's one. Is never lower than TIME_BUFFER_SIZE (in the Tobira Opencast module).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "tobira_sync_lag_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tobira Memory",
   "type": "timeseries",
   "description": "PSS: Proportional set size = all non-shared memory (USS) + a proportion of all shared memory.\nUSS: Unique Set Size = All non-shared memory.\nShared: All shared memory.\nRSS: Resident Set Size = all memory that is currently in RAM.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "tobira_proc_pss_bytes", "legendFormat": "PSS" },
    { "expr": "tobira_proc_uss_bytes", "legendFormat": "USS" },
    {
     "expr": "tobira_proc_shared_memory_bytes",
     "legendFormat": "Shared"
    },
    { "expr": "tobira_proc_rss_bytes", "legendFormat": "RSS" }
   ]
  },
  {
   "title": "Number of items in DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "tobira_num_items", "legendFormat": "{{item}}" }
   ]
  },
  {
   "title": "Num user sessions",
   "type": "timeseries",
   "description": "Tobira's user sessions, only useful if auth.mode is set to \"login-proxy\", i.e. if you're using Tobira's session management.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "tobira_num_user_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reponse times (index.html)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tobira_response_times_seconds_bucket{category=\"app\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Reponse times (GraphQL API)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tobira_response_times_seconds_bucket{category=\"graphql\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Reponse times (assets)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tobira_response_times_seconds_bucket{category=\"assets\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Reponse times (metrics)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tobira_response_times_seconds_bucket{category=\"metrics\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}