name: Check docs

on:
  pull_request:
    paths:
    - "docs/**"
    - ".github/workflows/check-docs.yml"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
        working-directory: docs
      - name: Build documentation
        run: npm run build
        working-directory: docs
